global using Azure;
global using EasyStocks.DTO.Requests;
global using EasyStocks.Service.AdminServices;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using EasyStocks.Infrastructure.Identity;
global using EasyStocks.Service;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.OpenApi.Models;
